### ISSUE TITLE
zoom not working???

### ISSUE THREAD

**Issue by geoherna** [imaginary-cloud/CameraManager#42] opened 2016-03-30 19:02 UTC
Hi, im running camera manager on XCode 7.2 using Swift 2.0 and am having an issue with zoom. I downloaded your example and everything seems to be working just fine, but when I add it to a blank project using Carthage, it wont zoom. I added a sub view to my view, created an outlet and the camera image shows up but when I pinch to zoom nothing happens. I'm wondering if I have to add some sort of setting to the cameraView or set some flag for zoom to work? Sorry if it's something obvious, im just not seeing it. 

Thank you.

**Comment by geoherna** [comment] 2016-03-30 20:10
OK, well it seems that this issue only happens when I initialize the camera in StillImage mode. Changing it to the following fixed it, not sure if this is intended behavior:

cameraManager.addPreviewLayerToView(cameraView, newCameraOutputMode: CameraOutputMode.VideoOnly)

**Comment by dpereira411** [comment] 2016-03-31 09:55
thanks for information, i will take a look :)

**Comment by FeelingCoding** [comment] 2016-04-08 10:33
+1 well it seems that this issue only happens when I initialize the camera in StillImage mode. Changing it to the following fixed it, not sure if this is intended behavior:

 public var cameraOutputMode = CameraOutputMode.StillImage {
        didSet {
            if cameraIsSetup {
                if cameraOutputMode != oldValue {
                    _setupOutputMode(cameraOutputMode, oldCameraOutputMode: oldValue)
                }
                _setupMaxZoomScale()
                _zoom(0)
            }
        }
    }

**Comment by ChrisStayte** [comment] 2016-05-08 21:37
has there been a fix to for this for still image mode?

**Comment by joelfsreis** [comment] 2016-05-12 16:08
This fix has been released in version 2.2.3 @geoherna 

Thanks for you suggestion @FeelingCoding

**Closed by joelfsreis** 2016-05-12 16:08 UTC
